plugins {
    id("java")
}

group = "de.bethibande"
version = "unspecified"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")

    compileOnly("org.projectlombok:lombok:1.18.38")
    annotationProcessor("org.projectlombok:lombok:1.18.38")

    compileOnly("org.jetbrains:annotations:26.0.2")

    implementation(projects.core)
    implementation(projects.serialNetty)
    // Needs to be defined *after* lombok.
    // Otherwise, the processor won't see the methods generated by lombok.
    annotationProcessor(projects.processor)

    implementation("io.netty:netty-buffer:4.2.0.Final")

    implementation("org.openjdk.jmh:jmh-core:1.37")
    annotationProcessor("org.openjdk.jmh:jmh-generator-annprocess:1.37")
}

tasks.test {
    useJUnitPlatform()
}